SUPABASE_URL = "https://lfndrjzkvkvwnjsogelh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmbmRyanprdmt2d25qc29nZWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1Njk3NjksImV4cCI6MjA4NTE0NTc2OX0.18Y4w-XAQjZAolf5LxFX_W-av5PYtDFtlxOEcVQUtes"
